modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Solarpanels/issues"
displayURL="https://u-team.info/mods/usefulsolarpanels"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulsolarpanels"
	version="${file.jarVersion}"
	displayName="Useful Solarpanels"
	updateJSONURL="https://api.u-team.info/update/usefulsolarpanels.json"
	description="This mod adds basic fe solar panels."
	
	[[dependencies.usefulsolarpanels]]
	    modId="forge"
	    mandatory=true
	    versionRange="[26.0.43,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulsolarpanels]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.2]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulsolarpanels]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[2.5.3.114,)"
	    ordering="NONE"
	    side="BOTH"